version: '3'
services:
  hyperf-skeleton:
    container_name: poc-hyperf
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
    privileged: true
    ports:
      - "9501:9501"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: hyperf_database
      DB_USERNAME: root
      DB_PASSWORD: root
      command: /bin/sh -c 'watch -d -n 1 "find /opt/www -name '\''config/*.php'\'' | xargs md5sum && php /opt/www/bin/hyperf.php start"'

    networks:
      - hyperf-network

  mysql:
    image: mysql:8
    container_name: poc-hyperf-database
    environment:
      MYSQL_DATABASE: hyperf_database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "hyperf-database:/var/lib/mysql"
    networks:
      - hyperf-network
networks:
  hyperf-network:
    driver: bridge

volumes:
  hyperf-database:

